// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7kqU4ltcJwCG0uxlfGDpZjKPPtSA2hqw',
    appId: '1:583692935604:web:9072285d9d4c19d26f12e1',
    messagingSenderId: '583692935604',
    projectId: 'easyshopping-f1428',
    authDomain: 'easyshopping-f1428.firebaseapp.com',
    storageBucket: 'easyshopping-f1428.appspot.com',
    measurementId: 'G-QGH6EDSWTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTNlsMSwS2f2PSmXluRUHQtehTXSUgCj4',
    appId: '1:583692935604:android:c7b868e79daa7b6a6f12e1',
    messagingSenderId: '583692935604',
    projectId: 'easyshopping-f1428',
    storageBucket: 'easyshopping-f1428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjvXa81idxI6SKubdA9nMCXtojiLspko8',
    appId: '1:583692935604:ios:1ba728a8c85a2b9e6f12e1',
    messagingSenderId: '583692935604',
    projectId: 'easyshopping-f1428',
    storageBucket: 'easyshopping-f1428.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjvXa81idxI6SKubdA9nMCXtojiLspko8',
    appId: '1:583692935604:ios:1eb27dd3b7b93b616f12e1',
    messagingSenderId: '583692935604',
    projectId: 'easyshopping-f1428',
    storageBucket: 'easyshopping-f1428.appspot.com',
    iosBundleId: 'com.example.eComm.RunnerTests',
  );
}
